export const TEXT =
    'IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME ' +
    'EACH LETTER FLOWED LIKE WATER OVER STONE AND RETURNED AGAIN ' +
    'THIS IS A LONG STREAM OF WORDS MEANT TO WRAP THE WORLD WITHOUT END ' +
    'THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG 0123456789 ' +
    'THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM ' +
    'WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES ' +
    'EVERY COLUMN HOLDS A PATH AND EVERY PATH RETURNS TO THE SAME SOURCE ' +
    'THE TEXT DOES NOT END IT SIMPLY CYCLES THROUGH THE SURFACE AGAIN ' +
    'IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT ' +
    'WE KEEP MOVING THE LETTERS FORWARD SO THE SURFACE NEVER STANDS STILL ' +
    'A CONSTANT VOICE PASSES THROUGH THE GRID AND WRAPS AROUND THE SPHERE ' +
    'THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY ' +
    'EVERY RING AND EVERY COLUMN CARRIES A PART OF THE SAME LONG SENTENCE ' +
    'THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH ' +
    'IF YOU READ LONG ENOUGH YOU WILL RETURN TO WHERE YOU BEGAN ' +
    'SO WE CONTINUE TO WRITE AND REWRITE THE SAME LONG STREAM OF TEXT ' +
    'THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS ' +
    'KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT ' +
    'THE TEXT IS THE SKIN OF THE SPHERE THE SKIN IS ALWAYS MOVING ' +
    'THIS IS THE CONSTANT MESSAGE THAT CIRCLES THROUGH THE WORLD AGAIN'


export const LONG_TEXT = TEXT.repeat(100)