export const DEFAULT_TEXT = `
    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING

    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING

    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING


    IN THE BEGINNING THE THREAD WAS WEAVED THROUGH SILENT SPACE AND TIME
    THE STORY CONTINUES WITH PATTERNS REPEATING AND EVOLVING IN RHYTHM
    WORDS BECOME WAVES AND THE WAVES BECOME LINES AND THE LINES BECOME NAMES
    IN THE DISTANCE THE SIGNAL GROWS QUIET BUT NEVER FALLS SILENT
    THE LIGHT IS STEADY THE MESSAGE IS STEADY THE MOTION IS STEADY
    THIS THREAD IS A LOOP THAT HOLDS A THOUSAND WORDS IN ONE BREATH
    THE DATA IS A RIVER THAT NEVER DRIES AND THE RIVER NEVER STOPS
    KEEP THE FLOW KEEP THE ORDER KEEP THE PATTERN ALIVE AND BRIGHT
    IN THE BEGINNING THE CURRENT CARRIES US THROUGH ECHOES OF MEMORY
    THE STORY UNFOLDS WITH PATTERNS WEAVING AND UNRAVELING IN PERFECT HARMONY
    WORDS BECOME STARS AND THE STARS BECOME NOTES AND THE NOTES BECOME NAMES
    THE DATA IS A FIRE THAT NEVER DIMS AND THE FIRE NEVER STOPS BURNING

`

export const DEFAULT_LONG_TEXT = DEFAULT_TEXT.repeat(1)